version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      start_period: 30s

  webapi:
    build:
      context: .
      dockerfile: backend/Hosts/WebAPI/Dockerfile
    container_name: webapi
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=HanhTestDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:80"

  workerservice:
    build:
      context: .
      dockerfile: backend/Hosts/WorkerService/Dockerfile
    container_name: workerservice
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=HanhTestDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;

volumes:
  sql-data:
