// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216001617_BreedDescriptionNVARCHARMAX")]
    partial class BreedDescriptionNVARCHARMAX
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Breeds", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Breed", b =>
                {
                    b.OwnsOne("Domain.Entities.BreedAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BreedDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BreedName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<bool>("Hypoallergenic")
                                .HasColumnType("bit");

                            b1.HasKey("BreedId");

                            b1.ToTable("Breeds");

                            b1.WithOwner()
                                .HasForeignKey("BreedId");

                            b1.OwnsOne("Domain.ValueObjects.ValueRange", "FemaleWeightRange", b2 =>
                                {
                                    b2.Property<Guid>("BreedAttributesBreedId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("FemaleWeightRangeMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("FemaleWeightRangeMin");

                                    b2.HasKey("BreedAttributesBreedId");

                                    b2.ToTable("Breeds");

                                    b2.WithOwner()
                                        .HasForeignKey("BreedAttributesBreedId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.ValueRange", "LifeRange", b2 =>
                                {
                                    b2.Property<Guid>("BreedAttributesBreedId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("LifeRangeMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("LifeRangeMin");

                                    b2.HasKey("BreedAttributesBreedId");

                                    b2.ToTable("Breeds");

                                    b2.WithOwner()
                                        .HasForeignKey("BreedAttributesBreedId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.ValueRange", "MaleWeightRange", b2 =>
                                {
                                    b2.Property<Guid>("BreedAttributesBreedId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("MaleWeightRangeMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("MaleWeightRangeMin");

                                    b2.HasKey("BreedAttributesBreedId");

                                    b2.ToTable("Breeds");

                                    b2.WithOwner()
                                        .HasForeignKey("BreedAttributesBreedId");
                                });

                            b1.Navigation("FemaleWeightRange")
                                .IsRequired();

                            b1.Navigation("LifeRange")
                                .IsRequired();

                            b1.Navigation("MaleWeightRange")
                                .IsRequired();
                        });

                    b.Navigation("Attributes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
